ip = '47.15.18.75';
country = 'CA';
this_domain = 'newchic.in';
last_url = 'https://www.newchic.in/';
ad_cookie_id = '-2053701946';
user_agent = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0';
ifrm = document.createElement('IFRAME');
url = 'https://js.admediasales.com/touch.html?';
ifrm.setAttribute('src', url );
 ifrm.style.display='none';ifrm.style.width = 0+'px';ifrm.style.height = 0+'px';
document.body.appendChild(ifrm);